# fly.toml app configuration file generated for portfolio-os-prod on 2025-10-19T01:16:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-os-prod'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
